### ISSUE TITLE
Using 3rd-party libraries in the cookbook examples?

### ISSUE THREAD

**Issue by uvtc** [HaxeFoundation/code-cookbook#134]
Is it ok to put examples into the cookbook that make use of libraries from haxelib (not in the standard library)?

For example, using [the thx.csv library](https://lib.haxe.org/p/thx.csv/) for working with csv files.

**Comment by markknol** [comment]
In general the cookbook is to demonstrate how Haxe works, that's why most examples are pure Haxe. But if that gets better illustrated when using a library, that should be fine. What kind of article are you thinking of?

**Comment by uvtc** [comment]
Ah. Thanks. I'd assumed the goal of the cookbook was instead to provide a wide-ranging catalog of "how to do $x" articles to give pointers to readers looking to do $x. Maybe that's too broad a goal though.

It sounds like the cookbook is intended to supplement the manual to some extent. That is, many chapters of the manual might contain "see-more-examples" links to relevant articles in the cookbook.

It may make sense to add a blurb to the cookbook's readme about what's expected to go into the cookbook.

**Comment by markknol** [comment]
Yeah, well we want "how to do x" articles. But we don't want to host documentation/tutorials for libraries, if that makes it more clear. Otherwise it would be probably to incomplete or it would suggest that some libraries are more important than others, because they are mentioned. And it is fair to not go in that direction. 
But as mentioned, if using a library helps on "how to do x", it shouldn't be a problem. For example; We also have an article where hxnodejs is used https://code.haxe.org/category/javascript/creating-node-server.html

**Comment by Gama11** [comment]
hxnodejs is one of the libs maintained by the HaxeFoundation org. Those libraries could probably be exceptions to the rule.

**Comment by ibilon** [comment]
Also hxnodejs is a "target library" to target node, a category which is also an exception.
