### ISSUE TITLE
Suggestion: Conditional compilation

### ISSUE THREAD

**Issue by Gamezpedia** [HaxeFoundation/code-cookbook#90]
typo :
![image](https://user-images.githubusercontent.com/1169093/32253519-2d4b0540-bebd-11e7-8a17-588425678f12.png)

Sources:
* https://code.haxe.org/category/beginner/conditional-compilation.html
* https://github.com/HaxeFoundation/code-cookbook/tree/master/./assets/content/cookbook/Beginner/conditional-compilation.md

@dstrekelj

**Comment by dstrekelj** [comment]
I'm sorry, I don't think I understand why this would be a typo. I set the `level` flag to 3 so that so that the condition of `level > 4` would evaluate to `false` and `level > 2` to `true`, printing the message "Welcome, super user!".

Granted, I probably should have used equality operators (e.g. `level == 2`) instead of relational ones, but the point proven by conditional compilation remains the same. Not sure why I wrote this way in the first place.

Really, any value could be used to demonstrate how conditional compilation works. Please, feel free to suggest an improvement or make a pull request with changes you deem appropriate!

**Comment by Gamezpedia** [comment]
ohhh no God damn it , sorry for the wrong claim i need to take more sleep, seriously i red it past midnight :S . it is perfect no need to change :)

**Comment by markknol** [comment]
No problem!

The good thing is that the automatic tagging of authors in the "report issue" link seems to works out :)
